  server:
    servlet:
      context-path: /api/v1

  spring:
    application:
      name: ECommerceAPI
    datasource:
      url: jdbc:postgresql://localhost:5432/ecommerce_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
    flyway:
      enabled: true
      locations: classpath:db/migration

  jwt:
    private:
      key: classpath:app.key
    public:
      key: classpath:app.pub